artifact-path: artifacts
seed: 42

data:
  gta-crash:
    source: kaggle
    type: datasets
    link: morizin/vision-crash-dataset


models:
  video-classifier:
    datasets: [ gta-crash ]
    type: video-2d-classification
    transforms:
      frames-per-clip: 20
      split: 
        type: skfold
        ratio: 0.8
      resize:
        height: 224
        width: 224
      normalize: false
      grayscale: true

    source-model: resnet18
    loss: binary-cross-entropy
    metrics:
      - accuracy
      - precision
      - recall
    
    optimizer: adam
    learning-rate: 0.001
    train-batch-size: 32
    valid-batch-size: 32
    n-epochs: 1
    gradient-accumulation-steps: 1
    outdir: video-classifier


